if(${WITH_CPP_SUGER})
  set(CPP11_DIR ${CMAKE_SOURCE_DIR}/src/cplusplus_suger/src/cpp11)
  set(CPP14_DIR ${CMAKE_SOURCE_DIR}/src/cplusplus_suger/src/cpp14)
  set(CPP17_DIR ${CMAKE_SOURCE_DIR}/src/cplusplus_suger/src/cpp17)
  set(CPP20_DIR ${CMAKE_SOURCE_DIR}/src/cplusplus_suger/src/cpp20)

  aux_source_directory(${CPP11_DIR}/src CPP11_SRCS)
  aux_source_directory(${CPP14_DIR}/src CPP14_SRCS)
  aux_source_directory(${CPP17_DIR}/src CPP17_SRCS)
  aux_source_directory(${CPP20_DIR}/src CPP20_SRCS)
endif()

message(STATUS "CPP11_DIR: ${CPP11_DIR}")
message(STATUS "CPP14_DIR: ${CPP14_DIR}")
message(STATUS "CPP17_DIR: ${CPP17_DIR}")
message(STATUS "CPP20_DIR: ${CPP20_DIR}")
